// Project scaffolding for the interactive setup wizard: init a starter
// agent-runtime.yaml so new projects are supervised from the start.
package integrate

import (
	"os"
	"path/filepath"
)

// starterConfigYAML is the agent-runtime.yaml written by ScaffoldConfig.
// Keep it in sync with the agent-runtime-ready skill template.
const starterConfigYAML = `# agent-runtime.yaml — declare the apps the agent-runtime MCP supervises.
# Generated by ` + "`agent-runtime`" + `. Edit freely; see the embedded skills
# for the full reference (agent-runtime-ready: SKILL.md, reference/agent-runtime-yaml.md).

runtime:
  # Base env layer: "login" (default) captures the login-shell env so venv and
  # version-manager shims reach managed processes. "none" uses os.Environ().
  shell_env: login

  # Global env layer, applied to every app/process (lowest precedence after
  # the base env).
  # env:
  #   - "LOG_LEVEL=info"

  # Per-stream log ring buffer size; get_logs reads from here.
  log_buffer_lines: 10000

  # SIGTERM -> SIGKILL grace period on stop_process.
  stop_grace: 5s

  # Optional durable SQLite log archive (logs survive runtime restarts).
  # log_store: sqlite

apps:
  # Each app is a name -> spec map. start_process(app="<name>") launches it.
  # Example (Python / FastAPI + uvicorn):
  # web:
  #   type: python
  #   workdir: ./
  #   command: ["myenv/bin/python", "-u", "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1"]
  #   env_file: .env
  #   env:
  #     - "PORT=8000"
  #     - "PYTHONUNBUFFERED=1"
`

// ScaffoldConfig writes a starter agent-runtime.yaml into dir unless one
// (agent-runtime.yaml or agent-runtime.yml) already exists there. Returns the
// config path and whether it was created.
func ScaffoldConfig(dir string) (path string, created bool, err error) {
	for _, name := range []string{"agent-runtime.yaml", "agent-runtime.yml"} {
		p := filepath.Join(dir, name)
		if _, err := os.Stat(p); err == nil {
			return p, false, nil
		}
	}
	path = filepath.Join(dir, "agent-runtime.yaml")
	if err := os.WriteFile(path, []byte(starterConfigYAML), 0o644); err != nil {
		return "", false, err
	}
	return path, true, nil
}
